### ISSUE TITLE
No notifications for new emails

### ISSUE THREAD

**Issue by Pointedstick** [flathub/org.mozilla.Thunderbird#11] opened 2018-04-07 14:20 UTC
The Flathub Thunderbird package does not send notifications for new emails the way distro package versions do.

**Comment by AdrianKoshka** [comment] 2018-04-07 17:29
I'm assuming you mean Thunderbird doesn't go through the DE's notification system?

**Comment by Alexander-Wilms** [comment] 2018-04-07 17:46
You could bundle https://addons.mozilla.org/de/thunderbird/addon/gnotifier

**Comment by AdrianKoshka** [comment] 2018-04-07 17:49
Would seem like a good solution for now. How do you bundle add-ons though?

**Comment by TingPing** [comment] 2018-04-08 04:08
I don't think you need to bundle an addon.. Adding `--talk-name=org.freedesktop.Notifications` will probably do.

**Comment by AdrianKoshka** [comment] 2018-04-08 04:10
Excellent, I'll make the changes and create a PR.

**Comment by TingPing** [comment] 2018-04-08 04:14
(Do test it, I don't use Thunderbird)

**Comment by Pointedstick** [comment] 2018-04-08 04:38
I can confirm that the "gnotifier" extension is indeed not necessary. However it does make the notifications more functional, adding an assortment of useful buttons such as "Delete" and "Mark as read". Shipping that extension by default would be more of a nice-to-have, though.

**Comment by AdrianKoshka** [comment] 2018-04-08 04:50
It's a creature comfort rather than a missing functionality. If a user wants it, they can install the extension, this is my opinion on the matter. If the notification portal works, I'll just use that. Unless I get high demand for this add-on to be included I don't see a point.

**Comment by AdrianKoshka** [comment] 2018-04-08 17:32
Hrmm, with Thunderbird installed within a CentOS7 VM with the new update (which should allow integrated notifications) I don't seem to be getting any notifications...how about you @Pointedstick ?

**Comment by AdrianKoshka** [comment] 2018-04-10 19:09
Thunderbird on Fedora Atomic Workstation with GNOME 3 doesn't seem to use GNOME notifications either oddly enough.

**Comment by AdrianKoshka** [comment] 2018-04-10 19:10
Can confirm that the notifications bus seems to be open. Perhaps this has to due with the lack of the use of portals in Thunderbird.
![bird](https://i.imgur.com/cIqb1Xv.png)

**Comment by nedrichards** [comment] 2018-04-10 19:17
It shouldn't - if it's using dbus then that should work. 

Have you run the app under --log-system-bus and --log-session-bus to see what it's talking to and then opening holes to whitelist that?

**Comment by AdrianKoshka** [comment] 2018-04-10 19:29
I ran Thunderbird (with those options), sent myself a mail (got a notification) and this is what was logged:

```
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake AddMatch for ca.desrt.dconf
C3: -> org.freedesktop.DBus fake GetNameOwner for ca.desrt.dconf
C4: -> org.freedesktop.DBus fake AddMatch for org.mozilla.Thunderbird
C5: -> org.freedesktop.DBus fake GetNameOwner for org.mozilla.Thunderbird
C6: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.Notifications
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.Notifications
C8: -> org.freedesktop.DBus fake AddMatch for org.a11y.*
C9: -> org.freedesktop.DBus fake AddMatch for org.mozilla.Thunderbird.*
C10: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.portal.*
C11: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C5
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
*SKIPPED*
B12: <- org.freedesktop.DBus return from C11
C12: -> org.freedesktop.DBus fake GetNameOwner for org.a11y.Bus
C13: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
C14: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
*SKIPPED*
C15: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C16: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 3)
*HIDDEN* (ping)
B13: <- org.freedesktop.DBus return from C12
*SKIPPED*
B14: <- org.freedesktop.DBus return from C13
*SKIPPED*
B15: <- org.freedesktop.DBus return from C14
*SKIPPED*
B16: <- org.freedesktop.DBus return from C15
B17: <- (no sender) return from C16
*REWRITTEN*
C17: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B18: <- (no sender) return from C17
*REWRITTEN*
C18: -> org.gtk.vfs.Daemon call org.gtk.vfs.Daemon.ListMonitorImplementations at /org/gtk/vfs/Daemon
*HIDDEN* (ping)
B19: <- (no sender) return from C18
*REWRITTEN*
C19: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 3)
*HIDDEN* (ping)
B20: <- (no sender) return from C19
*REWRITTEN*
C20: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B21: <- (no sender) return from C20
*REWRITTEN*
C21: -> org.gtk.vfs.Daemon call org.gtk.vfs.MountTracker.ListMountableInfo at /org/gtk/vfs/mounttracker
*HIDDEN* (ping)
B22: <- (no sender) return from C21
*REWRITTEN*
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake AddMatch for ca.desrt.dconf
C3: -> org.freedesktop.DBus fake GetNameOwner for ca.desrt.dconf
C4: -> org.freedesktop.DBus fake AddMatch for org.mozilla.Thunderbird
C5: -> org.freedesktop.DBus fake GetNameOwner for org.mozilla.Thunderbird
C6: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.Notifications
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.Notifications
C8: -> org.freedesktop.DBus fake AddMatch for org.a11y.*
C9: -> org.freedesktop.DBus fake AddMatch for org.mozilla.Thunderbird.*
C10: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.portal.*
C11: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C5
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
*SKIPPED*
B12: <- org.freedesktop.DBus return from C11
C12: -> org.freedesktop.DBus fake GetNameOwner for org.a11y.Bus
C13: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
C14: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
*SKIPPED*
B13: <- org.freedesktop.DBus return from C12
*SKIPPED*
B14: <- org.freedesktop.DBus return from C13
*SKIPPED*
B15: <- org.freedesktop.DBus return from C14
*SKIPPED*
[calBackendLoader] Using Thunderbird's builtin libical backend
C15: -> org.a11y.Bus call org.freedesktop.DBus.Properties.Get at /org/a11y/bus
B22: <- :1.10 return from C15
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
B23: <- org.freedesktop.DBus return from C22
C23: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B24: <- org.freedesktop.DBus return from C23
```

**Comment by Lvaskz** [comment] 2018-04-21 20:05
I have already installed. I proof it, but I noted the notification appears if thunderbird is running but if not the notification doesn't appears. Some idea what about? That is normal behavier? 
I am on linuxmint 18.3, 64 bit, cinnamon

**Comment by AdrianKoshka** [comment] 2018-04-21 20:42
I think this is perfectly normal behavior, if thunderbird is not running, then it can't send notifications, naturally.

**Comment by Lvaskz** [comment] 2018-04-21 20:46
Sorry, I should explain it better.  I send a email from my celular Phone to my email Google. But I waited see notification in my desktop, but I does not

**Comment by AdrianKoshka** [comment] 2018-04-21 20:49
So are you saying notifications only appear sometimes, but not others?

**Comment by Lvaskz** [comment] 2018-04-21 20:59
Yes, if thunderbird is running the notifications appear in my desktop, but if I close it and someone or myself, send me emails, the notifications simply do not appear.

**Comment by AdrianKoshka** [comment] 2018-04-21 20:59
What do you mean by `close`? As in minimize, or fully exit the application?

**Comment by Lvaskz** [comment] 2018-04-21 21:01
Fully exit. That is normal?

**Comment by Lvaskz** [comment] 2018-04-21 21:03
Some other email clients shows the notifications with the applications fully exit.

**Comment by AdrianKoshka** [comment] 2018-04-21 21:03
Yes. As far as I know. I don't think Thunderbird runs in the background?

**Comment by Lvaskz** [comment] 2018-04-21 21:39
Ok, thanks and sorry😁

**Comment by ovari** [comment] 2018-06-02 09:42
When installing Thunderbird on Linux Mint from the 'Software Manager', it also installs:
`Thunderbird-gnome-support`
The descriptions states:
> This package depends on the GNOME libraries which allow Thunderbird to take advantage of technologies such as GConf, GIO and libnotifiy

Without `Thunderbird-gnome-support` there are no DE specific notifications. The notifications are only shown above the Thunderbird window. The notification then disappears. If there is a different program whose window is above the Thunderbird window, you won't see the new email notification.

Another reason for having DE-specific notification is that the DE notification system will show new emails in the taskbar/panel of the DE until the notifications are cleared.

Can you please bundle `Thunderbird-gnome-support` into your Thunderbird flatpak?

Thank you

**Comment by AdrianKoshka** [comment] 2018-06-02 17:13
does `Thunderbird-gnome-support` work outside of GNOME? I.e. make Thunderbird integrates notifications with other DEs?

**Comment by ovari** [comment] 2018-06-03 02:07
> Libnotify is an implementation of the Desktop Notifications Specification which provides support for GTK+ and Qt applications and is desktop independent: it is already used by many open source apps like Evolution and Pidgin. Libnotify can be installed with the libnotify package.

https://wiki.archlinux.org/index.php/Desktop_notifications

There are non-GNOME (eg. KDE Plasma) notification servers using `libnotify`.
https://wiki.archlinux.org/index.php/Desktop_notifications#Notification_servers

`Thunderbird-gnome-support` includes the `libnotify` package. Perhaps you only need to include the `libnotify` package for DE notifications to work. What do you think?

**Comment by ovari** [comment] 2018-06-03 02:27
How and when can we test DE specific notifications for you?

**Comment by AdrianKoshka** [comment] 2018-06-03 03:03
Once I can get `libnotify` at least building, which shoudln't take long, I'll push my changes to the branch `libnotify-test`. Those interested can clone the repo and compile the flatpak themselve, or, perhaps, I'll just tar the exported repo. Then those interested can download the tar, extract it, add it as a local repo, and install the flatpak. I'd personally do the install portion within a VM (but that's because I run `i3wm` without any notification server, so spinning up a VM is probably a better way to test for me).

**Comment by AdrianKoshka** [comment] 2018-06-03 03:05
Well, I hit a bit of an unexpected roadblock:

```
========================================================================
Building module libnotify in /home/alc/git/github/flathub/org.mozilla.Thunderbird/.flatpak-builder/build/libnotify-1
========================================================================
/usr/bin/gnome-autogen.sh
***Warning*** PKG_NAME is deprecated, you may remove it from autogen.sh
Usage: autoconf [-h] [--help] [-m dir] [--macrodir=dir]
       [-l dir] [--localdir=dir] [--version] [template-file]
checking for automake >= 1.11.2...
  testing automake... found 1.15
checking for autoreconf >= 2.53...
  testing autoreconf... too old (found version 2.13)
***Error***: You must have autoreconf >= 2.53 installed
  to build .  Download the appropriate package for
  from your distribution or get the source tarball at
    http://ftp.gnu.org/pub/gnu/autoconf/autoconf-2.53.tar.xz

Error: module libnotify: module libnotify: Child process exited with code 1
make: *** [Makefile:8: build] Error 1
```

**Comment by AdrianKoshka** [comment] 2018-06-03 03:06
link: https://github.com/flathub/org.mozilla.Thunderbird/tree/libnotify-test

**Comment by ovari** [comment] 2018-06-03 09:36
In Terminal
```
$ sudo apt install git
$ sudo apt install flatpak-builder
$ mkdir repo
$ cd repo/
$ git clone -b libnotify-test --single-branch https://github.com/flathub/org.mozilla.Thunderbird/
$ flatpak-builder build org.mozilla.Thunderbird/org.mozilla.Thunderbird.json
error: org.gnome.Sdk 3.28 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 3.28
```

Does this help?

**Comment by AdrianKoshka** [comment] 2018-06-03 19:10
No, not at all. There are build instructions on this repos wiki.

**Comment by AdrianKoshka** [comment] 2018-06-06 23:27
https://send.firefox.com/download/9300b29568/#73FR1p5k0Feke-hUbZ4dmA I zipped up the `repo` folder for anyone who didn't want to compile.

steps to setup:

```shell
$ unzip repo.zip
$ flatpak --user remote-add --no-gpg-verify localtbrepo /home/user/repo
$ flatpak --user install localtbrepo org.mozila.Thunderbird
```

**Comment by AdrianKoshka** [comment] 2018-06-06 23:44
Results so far: (I'll update these as I test)

Fedora 28 with MATE: DE notifications aren't used

**Comment by ovari** [comment] 2018-06-08 09:37
```
~$ unzip repo.zip
~$ flatpak --user remote-add --no-gpg-verify localtbrepo /home/user/repo
~$ flatpak --user install localtbrepo org.mozila.Thunderbird
error: Error searching remote localtbrepo: Can't find ref org.mozila.Thunderbird
```

`user` was replaced by our name

Linux Mint 19 Cinnamon 64-bit beta

Do you have any suggestions?

Thank you

**Comment by AdrianKoshka** [comment] 2018-06-08 17:11
make sure that `/home/user/repo` is an actual directory? I've tested this with two VMs and it's worked just fine for me.

**Comment by ovari** [comment] 2018-06-09 21:40
**Thunderbird Beta Notes**
Version 60.0beta, first offered to channel users on March 26, 2018
These release notes apply to Thunderbird version 60 beta 7 released June 8th, 2018.
`changed    Native notifications on Linux are now re-enabled`
https://www.thunderbird.net/en-US/thunderbird/60.0beta/releasenotes/

Tested Thunderbird 60.0b7 and DE Notifications work on Linux Mint 18.3 Cinnamon 64-bit.

Since the next stable release of Thunderbird is Thunderbird 60 and expected this month (June 2018), seems that it should work with your flatpak without any additional work. Should Thunderbird 60.0b7 beta be tested with your flatpak or should we just wait for the official release?

Thank you

**Comment by AdrianKoshka** [comment] 2018-06-09 22:56
`> FIDO U2F support` FINALLY. Anyway, you're welcome to test this yourself, I'll probably just wait until the stable release, bump the version, see if notifications work.

**Comment by ovari** [comment] 2018-06-10 01:36
Agree with you. Please close this ticket and delete your `libnotify-test` branch.

**Comment by AdrianKoshka** [comment] 2018-06-10 08:48
I'll close it when I see it work, I will happily delete the branch though.

**Comment by AdrianKoshka** [comment] 2018-08-10 08:56
Anyone have any update on this, whether notifications are working for them or not with `v60` now? If I remember, I'll test later today.

**Comment by ovari** [comment] 2018-08-10 09:16
https://flathub.org/apps/details/org.mozilla.Thunderbird shows 52.9.1. Do you know when it will show 60.0 to enabling testing? Thank you @AdrianKoshka for releasing Thunderbird 60.0 flatpak.

**Comment by AdrianKoshka** [comment] 2018-08-10 09:18
It's 60, I know that, I don't know when flathub updates metadata, but the update has come through.

**Comment by ovari** [comment] 2018-08-10 12:14
Unfortunately, unable to test https://github.com/flathub/org.mozilla.Thunderbird/issues/46#issuecomment-412062244

**Comment by Erick555** [comment] 2019-09-16 22:49
I confirmed that new mail notifications work. In order to make it work you need two things:

1. Preferences > Advanced > General > Config Editor, set `mail.biff.use_system_alert` to `true` (default)
2. Preferences > General > Select Customize for "Show an alert" and set "Show New Mail alert for:"

**Closed by Erick555** 2019-09-16 22:49 UTC
Labels: enhancement

**Comment by ovari** [comment] 2019-09-17 21:55
@Erick555 added your comments at https://github.com/flathub/org.mozilla.Thunderbird/issues/11#issuecomment-531987872 to the README.md via https://github.com/flathub/org.mozilla.Thunderbird/pull/78

**Comment by iaacornus** [comment] 2022-05-05 17:15
The notification system doesn't work again in thunderbird flatpak in Fedora 35 silverblue
`Thunderbird                                      org.mozilla.Thunderbird                                        91.8.1              stable                flathub            system`

`mail.biff.use_system_alert` is set to `true`, and "Show new mail alert for:" is also turned on and set to 15s, and despite of issuing `sudo flatpak override --talk-name=org.freedesktop.Notifications org.mozilla.Thunderbird`. So notifications only show up after the app is opened.

**Comment by Erick555** [comment] 2022-05-05 20:35
> So notifications only show up after the app is opened.

Do you mean only when app is running or only when app window is focused? For me the notifications still show up when app is running in background.

**Comment by iaacornus** [comment] 2022-05-06 02:51
Only when the app is running.

**Comment by iaacornus** [comment] 2022-05-06 18:45
Makes sense, I thought it works like discord, like it does send notification even the window is closed.
