### ISSUE TITLE
Can't open links in default browser

### ISSUE THREAD

**Issue by longwuyuan** [flathub/org.mozilla.Thunderbird#18] opened 2018-04-15 13:33 UTC
Problem = Clicking a link in email does not open link in default browser. Clicking a link in email pops up a dialog to choose an application. Image is attached

$ flatpak --version
Flatpak 0.11.3

$ flatpak remotes
Name    Options
flathub system

$ flatpak list | grep thunder -i
org.mozilla.Thunderbird/x86_64/stable	system,current

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

![image](https://user-images.githubusercontent.com/5085914/38778950-d7e11c08-40de-11e8-8657-abd89ec5fab1.png)

**Comment by AdrianKoshka** [comment] 2018-04-15 18:53
Duplicate of #1

**Closed by AdrianKoshka** 2018-04-15 18:53 UTC
