### ISSUE TITLE
Can't interact with attachments

### ISSUE THREAD

**Issue by ndarilek** [flathub/org.mozilla.Thunderbird#19] opened 2018-04-17 14:34 UTC
Opening or saving attachments doesn't seem to work. I get no list of apps to choose from when opening, and xdg-open doesn't seem to work since I'm trying to open a docx and LibreOffice is installed as a flatpak. Saving just reports that the save fails.

Any thoughts on how I can get attachments out of my messages, short of installing non-flatpak Thunderbird?

Maybe Thunderbird can get read-write access to ~/Desktop? That seems to be where it wants to save attachments by default.

Thanks.

**Comment by AdrianKoshka** [comment] 2018-04-17 17:29
No, please use `XDG_DOWNLOAD`, and if you must, then with your file-manager move the file somewhere else, the security of not having `~` `RW` is worth it. Duplicate of #9. Though, you could make `~/Desktop` RW via `flatpak override`. On the issue of xdg-open not working, this is also a known issue (#1).

**Comment by AdrianKoshka** [comment] 2018-04-17 17:30
`XDG_DOWNLOAD` is `~/Downloads` if you didn't know.

**Closed** 2018-04-17 17:29 UTC
Labels: Duplicate of #9, duplicate

**Comment by ndarilek** [comment] 2018-04-17 18:10
Are you saying that all flatpaks have rw access to ~/Downloads by default?

To be clear, I never suggested that home be rw. I suggested that ~/Desktop be rw, though. My concern is that this is Thunderbird's default attachment save location, at least for me, and the package should probably either patch the default or embrace it. (Unless I'm mistaken about this default, that is...) Otherwise, folks will continue hitting this, and the idea that ~/Downloads is rw wasn't at all obvious to me when I suddenly found myself needing an attachment quickly but failing to save/open it.

**Comment by AdrianKoshka** [comment] 2018-04-17 18:59
No, I'm saying this specific flatpak has access to ~/Downloads by default. Yeah sorry for the saved reply about `~`. I didn't know (or don't know if) Thunderbird has a default save location. I could look into this though.

**Comment by TingPing** [comment] 2018-04-17 19:11
`~/Desktop` is an instant sandbox escape because you can write a desktop file there that executes code on the host.

**Comment by AdrianKoshka** [comment] 2018-04-17 19:11
Oh my, I didn't even think of that.

**Comment by TingPing** [comment] 2018-04-17 19:14
One could argue that escaping the sandbox doesn't really matter since you have `home:rw` and `network`. It can just upload your passwords, keys, wallets, etc.

**Comment by AdrianKoshka** [comment] 2018-04-17 19:15
`home` should be `ro` since I reverted that PR, I could check again...

**Comment by TingPing** [comment] 2018-04-17 19:15
Typo, sorry.

**Comment by AdrianKoshka** [comment] 2018-04-17 19:16
I know this is unrelated to this issue, be while we're here, perhaps we could set `~/.gnupg` and other sensitive locations to `--no-filesystem`?

**Comment by TingPing** [comment] 2018-04-17 19:18
> I know this is unrelated to this issue, be while we're here, perhaps we could set ~/.gnupg and other sensitive locations to --no-filesystem?

My thoughts: https://github.com/flatpak/flatpak/issues/1235

Really you need to get it using `GtkFileChooserNative` otherwise its all sort of theater IMO.

**Comment by TingPing** [comment] 2018-04-17 19:53
I assume they use the normal `GtkFileChooserDialog` in which case it is an extremely simple port.

**Comment by ovari** [comment] 2018-06-02 22:20
Firefox developers:
Bug 1466360 - Use "GtkFileChooserNative"
https://bugzilla.mozilla.org/show_bug.cgi?id=1466360
Blocks:
Bug 1278719 - Use Flatpak framework to distribute Firefox for Linux users
https://bugzilla.mozilla.org/show_bug.cgi?id=1278719
