### ISSUE TITLE
Can't save files / attachments

### ISSUE THREAD

**Issue by therealrobster** [flathub/org.mozilla.Thunderbird#35] opened 2018-05-02 00:58 UTC
Ubuntu 18.04

Hey there, I'm using the flatpak version. Seems good, mostly working well EXCEPT when I'm sent say, a spreadsheet file. I try open with and can't select Libreoffice (not in the list) (which is also a flatpak) and even worse, I can't save the ODS spreadsheet file.

I try save with the SAVE button and it doesn't appear in downloads. 

I choose SAVE AS and choose another location (say desktop) and get the error "_Unable to save the attachment. Please check your file name and try again later._"

Any ideas on what I can do?

Thank you

**Comment by therealrobster** [comment] 2018-05-02 01:12
UPDATE:  It turns out it's not just thunderbird.  I checked in Telegram Flatpak and it's the same and it turns out it's only when saving to the Desktop.  It saves files to the downloads folder just fine.  Maybe it's a flatpak restriction?

**Comment by AdrianKoshka** [comment] 2018-05-02 06:45
Please use `XDG_DOWNLOAD`, and if you must, then with your file-manager move the file somewhere else, the security of not having `~` `RW` is worth it. Duplicate of #9

**Comment by AdrianKoshka** [comment] 2018-05-02 06:48
Actually, let me clarify something before slapping this as a duplicate of #9. You are saving to `XDG_DOWNLOAD` (Otherwise known as `~/Downloads` on most distros) Right?

**Comment by therealrobster** [comment] 2018-05-02 06:59
Hi AdrianKoshka.  I'm just pressing the save and moving to my ~/Downloads folder or ~/Desktop folder.  I am not the most tech savvy.  I hope that helps.

**Comment by AdrianKoshka** [comment] 2018-05-02 07:03
Right, so saving to `~/Downloads` should work, as `XDG_DOWNLOAD` is set as read-write. Though, for security reasons, we prevent saving to any other location.

**Comment by therealrobster** [comment] 2018-05-02 07:05
Ahhh ok.  It would be great to have some kind of notification / message to let a standard end user know that.  Just a suggestion.  Loving your work, hope I was able to help in some small way.

**Comment by AdrianKoshka** [comment] 2018-05-02 07:06
Is your issue solved now? If so I can close it.

**Comment by therealrobster** [comment] 2018-05-02 07:08
Sure, I personally now know the restriction so I can ensure I save to Downloads.  Thanks for letting me know.

**Comment by AdrianKoshka** [comment] 2018-05-02 07:09
Of course. I do wish there was a...clean GUI method for an end-user to know what permissions a flatpak app has.

**Closed by AdrianKoshka** 2018-05-02 07:09 UTC
Labels: bug
