### ISSUE TITLE
Unable to save attachments

### ISSUE THREAD

**Issue by Pointedstick** [flathub/org.mozilla.Thunderbird#9] opened 2018-04-07 14:18 UTC
- Receive an email with attachments.
- Click on the "Save All" button
- Navigate to `~` and attempt to save the attachments.

Result:

![spectacle m10165](https://user-images.githubusercontent.com/1097249/38455820-8754bea2-3a3a-11e8-8c63-aff65416ccc1.png)

Looks like Thunderbird isn't using portals for this. Further evidence for this can be found in the fact that in my KDE Plasma environment, I get the native GTK file picker, and not the KDE one that the portal would supply. I have the `xdg-desktop-portal-kde` package installed.

**Comment by AdrianKoshka** [comment] 2018-04-07 17:27
fixed with #13

**Comment by AdrianKoshka** [comment] 2018-04-07 17:38
I will explain why `~` is `RO` while `XDG_DOWNLOAD` is `RW`. `~` is `RO` because we want people to be able to upload an attachment they have in their `~`, while `XDG_DOWNLOAD` is `RW` because we want people to download attachment(s) there.

**Comment by AdrianKoshka** [comment] 2018-04-07 17:52
>  I get the native GTK file picker, and not the KDE one that the portal would supply. I have the `xdg-desktop-portal-kde` package installed.

Sorry to show my ignorance of flatpak again, but would this issue be caused by the fact that Thunderbird is being built against the GNOME runtime?

**Comment by AdrianKoshka** [comment] 2018-04-07 18:45
Can confirm that saving things in `XDG_DOWNLOAD` works now, just did it myself with the updated build of the flatpak.

**Comment by AdrianKoshka** [comment] 2018-04-07 21:35
Seems from what @Exalm told me in the `#atomic` IRC room Thunderbird doesn't use flatpak portals, and the only way to fix this is to have Thunderbird use them. Also apparently Thunderbird uses GTK dialogs natively.

**Closed** 2018-04-07 21:40 UTC
Labels: bug, flaptak related

**Comment by Pointedstick** [comment] 2018-04-08 04:09
> Seems from what @Exalm told me in the #atomic IRC room Thunderbird doesn't use flatpak portals, and the only way to fix this is to have Thunderbird use them. Also apparently Thunderbird uses GTK dialogs natively.

Right, this is basically the root cause. When using a Portal, the user is able to choose any directory--such as `~`--to save in, and it Just Works™. Portal support is probably going to have to come from upstream, and may never arrive, sadly.

Until then, I think it would be humane to make `~` RW. Otherwise, you're going to get an endless number of duplicate reports of this. People *very commonly* like to save downloaded files to their Desktops and right in the root level of their home directories.

**Comment by AdrianKoshka** [comment] 2018-04-08 04:16
I suppose that would be the humane thing to, let me create a PR.

**Comment by AdrianKoshka** [comment] 2018-04-08 05:16
I've changed my mind and reverted the PR. I think the security is worth it. See my crude justification in #13 if you want.
